model:
  arch: proteinchat
  model_type: pretrain_vicuna
  freeze_protein_encoder: True
  freeze_qformer: True
  freeze_llama: True
  freeze_lp: True

  llama_model: "lmsys/vicuna-13b-v1.5"
  
  # generation configs
  prompt: ""

  max_txt_len: 405
  end_sym: "###"
  low_resource: True
  peft_ckpt: '' # stage-2 ckpt
  glm_load_path: "mignonjia/proteinglm-1b-mlm-sft" # HF path to the protein encoder and projection layer of ProteinChat
  stage1_ckpt: '' # do not need this if load from proteinglm-1b-mlm-sft model

datasets:
  seq:
    data_type: protein
    build_info:
      use_hf: True

run:
  task: protein_text_pretrain
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  printable: True

